// Professional QA: exercise the site's core interactions (not just static
// page-load). Runs once per URL on the primary browser+viewport combo.

import { finding, SEVERITY } from './util.mjs'

const FAKE = {
  name: 'QA Tester',
  firstName: 'QA',
  lastName: 'Tester',
  email: 'qa-test@example.invalid',
  phone: '+441234567890',
  company: 'Site QA Co',
  subject: 'Automated QA check — please ignore',
  message: 'This submission was generated by the local site-qa tool. Please ignore.',
  url: 'https://example.invalid',
}

function inputValueFor(input) {
  const name = ((input.getAttribute && input.getAttribute('name')) || input.name || '').toLowerCase()
  const id = ((input.getAttribute && input.getAttribute('id')) || input.id || '').toLowerCase()
  const placeholder = ((input.getAttribute && input.getAttribute('placeholder')) || input.placeholder || '').toLowerCase()
  const type = (input.type || '').toLowerCase()
  const key = `${name} ${id} ${placeholder}`

  if (type === 'email' || /email/.test(key)) return FAKE.email
  if (type === 'tel' || /phone|mobile|tel/.test(key)) return FAKE.phone
  if (type === 'url' || /website|url/.test(key)) return FAKE.url
  if (type === 'number') return '42'
  if (type === 'date') return '2026-01-01'
  if (/first.?name/.test(key)) return FAKE.firstName
  if (/last.?name|surname/.test(key)) return FAKE.lastName
  if (/\bname\b/.test(key)) return FAKE.name
  if (/company|organisation|organization|business/.test(key)) return FAKE.company
  if (/subject/.test(key)) return FAKE.subject
  if (/message|comment|enquiry|inquiry|notes?\b/.test(key)) return FAKE.message
  return 'QA test value'
}

export async function runInteractions({ page, url }) {
  const findings = []
  const log = []
  const preErrors = []
  const preRequests = []

  const onError = (e) => preErrors.push({ name: e.name, message: e.message })
  const onConsole = (msg) => {
    if (msg.type() === 'error') preErrors.push({ name: 'console', message: msg.text() })
  }
  const onRequest = (req) => {
    if (['POST', 'PUT', 'PATCH'].includes(req.method())) {
      preRequests.push({ url: req.url(), method: req.method() })
    }
  }

  page.on('pageerror', onError)
  page.on('console', onConsole)
  page.on('request', onRequest)

  // --- 1. Primary CTA: find the most prominent above-the-fold button ---
  try {
    const target = await page.evaluate(() => {
      const vw = window.innerWidth
      const vh = window.innerHeight
      const candidates = []
      const els = document.querySelectorAll('a, button, [role="button"]')
      for (const el of els) {
        const r = el.getBoundingClientRect()
        if (r.width < 40 || r.height < 24) continue
        if (r.top < 0 || r.top > vh * 1.2) continue
        if (r.right < 0 || r.left > vw) continue
        const style = window.getComputedStyle(el)
        if (style.visibility === 'hidden' || style.display === 'none' || style.opacity === '0') continue
        const text = (el.textContent || '').trim()
        if (!text || text.length > 60) continue
        // Skip nav-ish links
        const inNav = el.closest('nav, header [role="navigation"]')
        const area = r.width * r.height
        const hasBg = style.backgroundColor && style.backgroundColor !== 'rgba(0, 0, 0, 0)' && style.backgroundColor !== 'transparent'
        let score = area
        if (hasBg) score *= 1.5
        if (/get.?start|contact|book|sign.?up|request|buy|try|demo|quote|call|learn more/i.test(text)) score *= 2
        if (inNav) score *= 0.3
        candidates.push({ score, text, tag: el.tagName.toLowerCase(), x: r.left + r.width / 2, y: r.top + r.height / 2 })
      }
      candidates.sort((a, b) => b.score - a.score)
      return candidates[0] || null
    })

    if (target) {
      log.push({ step: 'cta-found', detail: target })
      const beforeUrl = page.url()
      const errorsBefore = preErrors.length

      await page.mouse.click(target.x, target.y, { delay: 40 })
      await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {})
      await page.waitForTimeout(400)

      const afterUrl = page.url()
      const newErrors = preErrors.slice(errorsBefore)

      if (newErrors.length) {
        findings.push(finding(SEVERITY.ERROR, 'interaction-cta-error',
          `Clicking primary CTA "${target.text}" produced ${newErrors.length} error(s)`,
          { cta: target.text, errors: newErrors.slice(0, 3) }))
      } else {
        log.push({ step: 'cta-clicked', cta: target.text, navigated: beforeUrl !== afterUrl, afterUrl })
      }

      // Return to the page under test for the form check
      if (afterUrl !== beforeUrl) {
        await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {})
      }
    } else {
      log.push({ step: 'cta-not-found' })
    }
  } catch (err) {
    findings.push(finding(SEVERITY.WARN, 'interaction-cta-failed',
      `CTA interaction failed: ${err.message}`))
  }

  // --- 2. Form submit: find a form with real inputs, fill + submit ---
  try {
    // Block real submissions: intercept network sends to same-origin form endpoints
    await page.route('**/*', (route) => {
      const req = route.request()
      if (['POST', 'PUT', 'PATCH'].includes(req.method())) {
        // Fulfil without hitting the real backend
        return route.fulfill({ status: 200, contentType: 'application/json', body: '{"qa":"intercepted"}' })
      }
      return route.continue()
    })

    const formInfo = await page.evaluate(() => {
      const forms = [...document.querySelectorAll('form')]
      for (const form of forms) {
        const r = form.getBoundingClientRect()
        if (r.width === 0 || r.height === 0) continue
        const inputs = [...form.querySelectorAll('input, textarea, select')].filter((i) => {
          const type = (i.type || '').toLowerCase()
          return !['hidden', 'submit', 'button', 'file', 'image'].includes(type)
        })
        if (inputs.length === 0) continue
        return {
          selector: form.id ? `#${form.id}` : null,
          action: form.action || null,
          method: (form.method || 'get').toLowerCase(),
          fields: inputs.map((i) => ({
            tag: i.tagName.toLowerCase(),
            type: (i.type || '').toLowerCase(),
            name: i.name || null,
            id: i.id || null,
            placeholder: i.placeholder || null,
            required: i.required || false,
          })),
        }
      }
      return null
    })

    if (formInfo) {
      log.push({ step: 'form-found', fields: formInfo.fields.length, action: formInfo.action })
      const errorsBefore = preErrors.length

      for (const field of formInfo.fields) {
        const value = inputValueFor(field)
        const sel = field.id
          ? `#${field.id}`
          : field.name
            ? `[name="${field.name}"]`
            : `${field.tag}[type="${field.type || 'text'}"]`
        try {
          if (field.tag === 'select') {
            const loc = page.locator(sel).first()
            const opts = await loc.locator('option').all()
            if (opts.length > 1) await loc.selectOption({ index: 1 })
          } else if (field.type === 'checkbox' || field.type === 'radio') {
            await page.locator(sel).first().check({ timeout: 1000, force: true })
          } else {
            await page.locator(sel).first().fill(value, { timeout: 1000 })
          }
        } catch {
          // Fall back silently — one stubborn field shouldn't abort the whole check
        }
      }

      const submitBtn = page.locator('form button[type="submit"], form input[type="submit"], form button:not([type])').first()
      const hadSubmit = await submitBtn.isVisible({ timeout: 500 }).catch(() => false)
      if (hadSubmit) {
        await submitBtn.click({ timeout: 2000, force: true }).catch(() => {})
        await page.waitForTimeout(800)
        await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {})
      }

      const newErrors = preErrors.slice(errorsBefore)
      if (newErrors.length) {
        findings.push(finding(SEVERITY.ERROR, 'interaction-form-error',
          `Submitting form produced ${newErrors.length} error(s)`,
          { errors: newErrors.slice(0, 3), form: formInfo }))
      } else {
        log.push({ step: 'form-submitted', fields: formInfo.fields.length })
      }
    } else {
      log.push({ step: 'form-not-found' })
    }
  } catch (err) {
    findings.push(finding(SEVERITY.WARN, 'interaction-form-failed',
      `Form interaction failed: ${err.message}`))
  } finally {
    await page.unroute('**/*').catch(() => {})
  }

  // --- 3. Mobile nav toggle + *verify* panel actually reveals links ---
  try {
    const vw = page.viewportSize()?.width ?? 0
    if (vw > 0 && vw < 900) {
      const togglers = [
        'button[aria-label*="menu" i]',
        'button[aria-controls*="nav" i]',
        'button[aria-expanded="false"]',
        'button.hamburger',
        'button.menu-toggle',
        '[data-toggle="menu"]',
      ]
      let clicked = null
      for (const sel of togglers) {
        const loc = page.locator(sel).first()
        if (await loc.isVisible({ timeout: 200 }).catch(() => false)) {
          const errorsBefore = preErrors.length
          await loc.click({ timeout: 1000, force: true }).catch(() => {})
          await page.waitForTimeout(400)
          clicked = sel
          const newErrors = preErrors.slice(errorsBefore)
          if (newErrors.length) {
            findings.push(finding(SEVERITY.ERROR, 'mobile-menu-click-error',
              `Clicking mobile menu toggle produced ${newErrors.length} error(s)`,
              { selector: sel, errors: newErrors.slice(0, 3) }))
          }
          break
        }
      }

      if (clicked) {
        const panel = await page.evaluate((toggleSel) => {
          const btn = document.querySelector(toggleSel)
          if (!btn) return { reason: 'toggle-not-found' }
          const controls = btn.getAttribute('aria-controls')
          let panelEl = controls ? document.getElementById(controls) : null
          if (!panelEl) {
            // Fall back: a nav/ul inside an expanded=true ancestor, or visible nav in body
            panelEl = document.querySelector('[aria-expanded="true"] nav, [aria-expanded="true"] ul')
              || [...document.querySelectorAll('nav, [role="navigation"]')].find((n) => {
                const r = n.getBoundingClientRect()
                const cs = getComputedStyle(n)
                return r.height > 50 && cs.visibility !== 'hidden' && cs.display !== 'none'
              })
          }
          if (!panelEl) return { reason: 'panel-not-found' }
          const r = panelEl.getBoundingClientRect()
          const links = [...panelEl.querySelectorAll('a[href]')].filter((a) => {
            const ar = a.getBoundingClientRect()
            const cs = getComputedStyle(a)
            return ar.width > 0 && ar.height > 0 && cs.visibility !== 'hidden' && cs.display !== 'none'
          })
          return {
            visible: r.height > 10 && r.width > 10,
            linkCount: links.length,
            height: Math.round(r.height),
            firstLink: links[0] ? (links[0].getAttribute('href') || '') : null,
          }
        }, clicked)

        if (panel.reason === 'panel-not-found') {
          findings.push(finding(SEVERITY.ERROR, 'mobile-menu-no-panel',
            `Clicking ${clicked} did not reveal a navigation panel (no aria-controls target + no visible nav)`,
            { selector: clicked }))
        } else if (!panel.visible || panel.linkCount === 0) {
          findings.push(finding(SEVERITY.ERROR, 'mobile-menu-empty',
            `Mobile menu opened but contains ${panel.linkCount} visible link(s). Expected: nav links. Repro: at mobile viewport (${vw}px), click ${clicked}`,
            { selector: clicked, linkCount: panel.linkCount, panelHeight: panel.height }))
        } else {
          log.push({ step: 'mobile-menu-verified', selector: clicked, links: panel.linkCount })
        }
      } else {
        log.push({ step: 'mobile-menu-not-found' })
      }
    }
  } catch (err) {
    findings.push(finding(SEVERITY.WARN, 'interaction-menu-failed',
      `Mobile menu check failed: ${err.message}`))
  }

  // --- 4. Nav link health: HEAD each primary-nav link, check hash targets ---
  try {
    const navLinks = await page.evaluate(() => {
      const nav = document.querySelector('header nav, nav[role="navigation"], header [role="navigation"], nav')
      if (!nav) return []
      return [...nav.querySelectorAll('a[href]')]
        .map((a) => a.getAttribute('href'))
        .filter((h) => h && h !== '#' && !h.startsWith('javascript:'))
        .slice(0, 15)
    })
    for (const href of navLinks) {
      if (href.startsWith('#')) {
        const id = href.slice(1)
        if (!id) continue
        const exists = await page.evaluate((i) => !!document.getElementById(i), id)
        if (!exists) {
          findings.push(finding(SEVERITY.WARN, 'nav-hash-target-missing',
            `Nav link points to #${id} but no element with that id exists`,
            { href, id }))
        }
        continue
      }
      let resolved
      try { resolved = new URL(href, page.url()).href } catch { continue }
      try {
        const res = await page.request.fetch(resolved, { method: 'HEAD', timeout: 8000 })
        if (res.status() >= 400) {
          findings.push(finding(
            res.status() >= 500 ? SEVERITY.ERROR : SEVERITY.WARN,
            'nav-link-broken',
            `Nav link returns HTTP ${res.status()}: ${resolved}`,
            { href, status: res.status() }))
        }
      } catch (err) {
        findings.push(finding(SEVERITY.WARN, 'nav-link-unreachable',
          `Nav link unreachable: ${resolved} (${err.message})`,
          { href, error: err.message }))
      }
    }
    log.push({ step: 'nav-links-checked', count: navLinks.length })
  } catch (err) {
    // Non-fatal: nav-link health is additive
  }

  // --- 5. Sticky header sanity: scroll and verify header stays usable ---
  try {
    const headerInfo = await page.evaluate(() => {
      const h = document.querySelector('header, [role="banner"]')
      if (!h) return null
      const cs = getComputedStyle(h)
      const r = h.getBoundingClientRect()
      return {
        position: cs.position,
        top: Math.round(r.top),
        height: Math.round(r.height),
        sticky: cs.position === 'sticky' || cs.position === 'fixed',
        zIndex: cs.zIndex,
      }
    })
    if (headerInfo && headerInfo.sticky) {
      await page.evaluate(() => window.scrollTo(0, 800))
      await page.waitForTimeout(200)
      const afterScroll = await page.evaluate(() => {
        const h = document.querySelector('header, [role="banner"]')
        if (!h) return null
        const r = h.getBoundingClientRect()
        const cs = getComputedStyle(h)
        return {
          top: Math.round(r.top),
          height: Math.round(r.height),
          bottom: Math.round(r.bottom),
          hidden: cs.visibility === 'hidden' || cs.display === 'none' || parseFloat(cs.opacity) === 0,
        }
      })
      await page.evaluate(() => window.scrollTo(0, 0))
      if (afterScroll) {
        if (afterScroll.hidden) {
          findings.push(finding(SEVERITY.WARN, 'sticky-header-hidden-on-scroll',
            `Header is position:${headerInfo.position} but becomes hidden after scrolling`,
            { before: headerInfo, after: afterScroll }))
        } else if (afterScroll.top > 5 || afterScroll.bottom < 0) {
          findings.push(finding(SEVERITY.WARN, 'sticky-header-off-screen',
            `Sticky header not pinned after scroll (top=${afterScroll.top}, bottom=${afterScroll.bottom})`,
            { before: headerInfo, after: afterScroll }))
        } else {
          const vh = page.viewportSize()?.height ?? 0
          if (vh > 0 && afterScroll.height > vh * 0.3) {
            findings.push(finding(SEVERITY.WARN, 'sticky-header-too-tall',
              `Sticky header ${afterScroll.height}px covers ${Math.round(afterScroll.height / vh * 100)}% of viewport height`,
              { headerHeight: afterScroll.height, viewportHeight: vh }))
          }
          log.push({ step: 'sticky-header-ok', height: afterScroll.height })
        }
      }
    }
  } catch {}

  // --- 6. Form validation UX: submit empty, submit invalid email ---
  try {
    const hasForm = await page.locator('form').first().isVisible({ timeout: 300 }).catch(() => false)
    if (hasForm) {
      // Intercept so nothing leaves the machine
      await page.route('**/*', (route) => {
        const req = route.request()
        if (['POST', 'PUT', 'PATCH'].includes(req.method())) {
          return route.fulfill({ status: 200, contentType: 'application/json', body: '{"qa":"intercepted"}' })
        }
        return route.continue()
      })

      // Reload to get a clean form state
      await page.reload({ waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {})
      await page.waitForTimeout(300)

      // Submit empty
      const submitEmpty = page.locator('form button[type="submit"], form input[type="submit"], form button:not([type])').first()
      if (await submitEmpty.isVisible({ timeout: 500 }).catch(() => false)) {
        await submitEmpty.click({ timeout: 1500, force: true }).catch(() => {})
        await page.waitForTimeout(400)
        const emptyValidation = await page.evaluate(() => {
          const form = document.querySelector('form')
          if (!form) return { ok: false, reason: 'no-form' }
          const invalids = form.querySelectorAll(':invalid')
          const ariaInvalid = form.querySelectorAll('[aria-invalid="true"]')
          const errorText = [...form.querySelectorAll('[class*="error" i], [role="alert"], [aria-live]')]
            .filter((el) => {
              const r = el.getBoundingClientRect()
              return r.width > 0 && r.height > 0 && (el.textContent || '').trim().length > 0
            })
          const hasRequired = form.querySelectorAll('[required]').length
          return {
            invalidCount: invalids.length,
            ariaInvalidCount: ariaInvalid.length,
            errorTextCount: errorText.length,
            hasRequired,
          }
        })
        if (emptyValidation.hasRequired > 0
            && emptyValidation.invalidCount === 0
            && emptyValidation.ariaInvalidCount === 0
            && emptyValidation.errorTextCount === 0) {
          findings.push(finding(SEVERITY.WARN, 'form-no-empty-validation',
            `Form submits with empty required fields — no :invalid, aria-invalid, or error UI surfaced`,
            emptyValidation))
        } else {
          log.push({ step: 'form-empty-validation-ok', ...emptyValidation })
        }
      }

      // Invalid email test
      const emailField = page.locator('form input[type="email"], form input[name*="email" i]').first()
      if (await emailField.isVisible({ timeout: 300 }).catch(() => false)) {
        await emailField.fill('not-an-email', { timeout: 1000 }).catch(() => {})
        if (await submitEmpty.isVisible({ timeout: 300 }).catch(() => false)) {
          await submitEmpty.click({ timeout: 1500, force: true }).catch(() => {})
          await page.waitForTimeout(400)
        }
        const emailValidation = await page.evaluate(() => {
          const input = document.querySelector('form input[type="email"], form input[name*="email" i]')
          if (!input) return null
          return { valid: input.validity?.valid ?? null, value: input.value }
        })
        if (emailValidation && emailValidation.valid === true) {
          findings.push(finding(SEVERITY.WARN, 'form-accepts-invalid-email',
            `Email field accepts invalid value "${emailValidation.value}" (missing type="email" or pattern validation)`,
            emailValidation))
        }
      }

      await page.unroute('**/*').catch(() => {})
    }
  } catch {}

  // --- 7. Focus-ring visibility: Tab through first N focusables, verify outline/shadow ---
  try {
    await page.evaluate(() => window.scrollTo(0, 0))
    // Start from a known anchor
    await page.evaluate(() => (document.body.tabIndex = -1, document.body.focus()))
    const ringSample = []
    const SAMPLE = 8
    for (let i = 0; i < SAMPLE; i++) {
      await page.keyboard.press('Tab')
      const info = await page.evaluate(() => {
        const el = document.activeElement
        if (!el || el === document.body) return null
        const cs = getComputedStyle(el)
        const hasOutline = cs.outlineStyle && cs.outlineStyle !== 'none' && parseFloat(cs.outlineWidth) > 0
        const hasShadow = cs.boxShadow && cs.boxShadow !== 'none'
        const hasRing = hasOutline || hasShadow
        const selector = el.id
          ? `#${el.id}`
          : `${el.tagName.toLowerCase()}${el.className && typeof el.className === 'string' ? '.' + el.className.trim().split(/\s+/).slice(0, 2).join('.') : ''}`
        return { tag: el.tagName.toLowerCase(), selector, hasRing, outline: cs.outline, boxShadow: cs.boxShadow.slice(0, 80) }
      })
      if (info) ringSample.push(info)
    }
    const missing = ringSample.filter((r) => !r.hasRing)
    if (missing.length > 0) {
      findings.push(finding(SEVERITY.WARN, 'no-focus-ring',
        `${missing.length} of ${ringSample.length} tabbable elements have no visible focus indicator (outline:none + no box-shadow)`,
        { sample: missing.slice(0, 5) }))
    } else if (ringSample.length > 0) {
      log.push({ step: 'focus-rings-ok', sampled: ringSample.length })
    }
  } catch {}

  page.off('pageerror', onError)
  page.off('console', onConsole)
  page.off('request', onRequest)

  return { findings, log }
}
