// Professional QA: exercise the site's core interactions (not just static
// page-load). Runs once per URL on the primary browser+viewport combo.

import { finding, SEVERITY } from './util.mjs'

const FAKE = {
  name: 'QA Tester',
  firstName: 'QA',
  lastName: 'Tester',
  email: 'qa-test@example.invalid',
  phone: '+441234567890',
  company: 'Site QA Co',
  subject: 'Automated QA check — please ignore',
  message: 'This submission was generated by the local site-qa tool. Please ignore.',
  url: 'https://example.invalid',
}

function inputValueFor(input) {
  const name = ((input.getAttribute && input.getAttribute('name')) || input.name || '').toLowerCase()
  const id = ((input.getAttribute && input.getAttribute('id')) || input.id || '').toLowerCase()
  const placeholder = ((input.getAttribute && input.getAttribute('placeholder')) || input.placeholder || '').toLowerCase()
  const type = (input.type || '').toLowerCase()
  const key = `${name} ${id} ${placeholder}`

  if (type === 'email' || /email/.test(key)) return FAKE.email
  if (type === 'tel' || /phone|mobile|tel/.test(key)) return FAKE.phone
  if (type === 'url' || /website|url/.test(key)) return FAKE.url
  if (type === 'number') return '42'
  if (type === 'date') return '2026-01-01'
  if (/first.?name/.test(key)) return FAKE.firstName
  if (/last.?name|surname/.test(key)) return FAKE.lastName
  if (/\bname\b/.test(key)) return FAKE.name
  if (/company|organisation|organization|business/.test(key)) return FAKE.company
  if (/subject/.test(key)) return FAKE.subject
  if (/message|comment|enquiry|inquiry|notes?\b/.test(key)) return FAKE.message
  return 'QA test value'
}

export async function runInteractions({ page, url }) {
  const findings = []
  const log = []
  const preErrors = []
  const preRequests = []

  const onError = (e) => preErrors.push({ name: e.name, message: e.message })
  const onConsole = (msg) => {
    if (msg.type() === 'error') preErrors.push({ name: 'console', message: msg.text() })
  }
  const onRequest = (req) => {
    if (['POST', 'PUT', 'PATCH'].includes(req.method())) {
      preRequests.push({ url: req.url(), method: req.method() })
    }
  }

  page.on('pageerror', onError)
  page.on('console', onConsole)
  page.on('request', onRequest)

  // --- 1. Primary CTA: find the most prominent above-the-fold button ---
  try {
    const target = await page.evaluate(() => {
      const vw = window.innerWidth
      const vh = window.innerHeight
      const candidates = []
      const els = document.querySelectorAll('a, button, [role="button"]')
      for (const el of els) {
        const r = el.getBoundingClientRect()
        if (r.width < 40 || r.height < 24) continue
        if (r.top < 0 || r.top > vh * 1.2) continue
        if (r.right < 0 || r.left > vw) continue
        const style = window.getComputedStyle(el)
        if (style.visibility === 'hidden' || style.display === 'none' || style.opacity === '0') continue
        const text = (el.textContent || '').trim()
        if (!text || text.length > 60) continue
        // Skip nav-ish links
        const inNav = el.closest('nav, header [role="navigation"]')
        const area = r.width * r.height
        const hasBg = style.backgroundColor && style.backgroundColor !== 'rgba(0, 0, 0, 0)' && style.backgroundColor !== 'transparent'
        let score = area
        if (hasBg) score *= 1.5
        if (/get.?start|contact|book|sign.?up|request|buy|try|demo|quote|call|learn more/i.test(text)) score *= 2
        if (inNav) score *= 0.3
        candidates.push({ score, text, tag: el.tagName.toLowerCase(), x: r.left + r.width / 2, y: r.top + r.height / 2 })
      }
      candidates.sort((a, b) => b.score - a.score)
      return candidates[0] || null
    })

    if (target) {
      log.push({ step: 'cta-found', detail: target })
      const beforeUrl = page.url()
      const errorsBefore = preErrors.length

      await page.mouse.click(target.x, target.y, { delay: 40 })
      await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {})
      await page.waitForTimeout(400)

      const afterUrl = page.url()
      const newErrors = preErrors.slice(errorsBefore)

      if (newErrors.length) {
        findings.push(finding(SEVERITY.ERROR, 'interaction-cta-error',
          `Clicking primary CTA "${target.text}" produced ${newErrors.length} error(s)`,
          { cta: target.text, errors: newErrors.slice(0, 3) }))
      } else {
        log.push({ step: 'cta-clicked', cta: target.text, navigated: beforeUrl !== afterUrl, afterUrl })
      }

      // Return to the page under test for the form check
      if (afterUrl !== beforeUrl) {
        await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {})
      }
    } else {
      log.push({ step: 'cta-not-found' })
    }
  } catch (err) {
    findings.push(finding(SEVERITY.WARN, 'interaction-cta-failed',
      `CTA interaction failed: ${err.message}`))
  }

  // --- 2. Form submit: find a form with real inputs, fill + submit ---
  try {
    // Block real submissions: intercept network sends to same-origin form endpoints
    await page.route('**/*', (route) => {
      const req = route.request()
      if (['POST', 'PUT', 'PATCH'].includes(req.method())) {
        // Fulfil without hitting the real backend
        return route.fulfill({ status: 200, contentType: 'application/json', body: '{"qa":"intercepted"}' })
      }
      return route.continue()
    })

    const formInfo = await page.evaluate(() => {
      const forms = [...document.querySelectorAll('form')]
      for (const form of forms) {
        const r = form.getBoundingClientRect()
        if (r.width === 0 || r.height === 0) continue
        const inputs = [...form.querySelectorAll('input, textarea, select')].filter((i) => {
          const type = (i.type || '').toLowerCase()
          return !['hidden', 'submit', 'button', 'file', 'image'].includes(type)
        })
        if (inputs.length === 0) continue
        return {
          selector: form.id ? `#${form.id}` : null,
          action: form.action || null,
          method: (form.method || 'get').toLowerCase(),
          fields: inputs.map((i) => ({
            tag: i.tagName.toLowerCase(),
            type: (i.type || '').toLowerCase(),
            name: i.name || null,
            id: i.id || null,
            placeholder: i.placeholder || null,
            required: i.required || false,
          })),
        }
      }
      return null
    })

    if (formInfo) {
      log.push({ step: 'form-found', fields: formInfo.fields.length, action: formInfo.action })
      const errorsBefore = preErrors.length

      for (const field of formInfo.fields) {
        const value = inputValueFor(field)
        const sel = field.id
          ? `#${field.id}`
          : field.name
            ? `[name="${field.name}"]`
            : `${field.tag}[type="${field.type || 'text'}"]`
        try {
          if (field.tag === 'select') {
            const loc = page.locator(sel).first()
            const opts = await loc.locator('option').all()
            if (opts.length > 1) await loc.selectOption({ index: 1 })
          } else if (field.type === 'checkbox' || field.type === 'radio') {
            await page.locator(sel).first().check({ timeout: 1000, force: true })
          } else {
            await page.locator(sel).first().fill(value, { timeout: 1000 })
          }
        } catch {
          // Fall back silently — one stubborn field shouldn't abort the whole check
        }
      }

      const submitBtn = page.locator('form button[type="submit"], form input[type="submit"], form button:not([type])').first()
      const hadSubmit = await submitBtn.isVisible({ timeout: 500 }).catch(() => false)
      if (hadSubmit) {
        await submitBtn.click({ timeout: 2000, force: true }).catch(() => {})
        await page.waitForTimeout(800)
        await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {})
      }

      const newErrors = preErrors.slice(errorsBefore)
      if (newErrors.length) {
        findings.push(finding(SEVERITY.ERROR, 'interaction-form-error',
          `Submitting form produced ${newErrors.length} error(s)`,
          { errors: newErrors.slice(0, 3), form: formInfo }))
      } else {
        log.push({ step: 'form-submitted', fields: formInfo.fields.length })
      }
    } else {
      log.push({ step: 'form-not-found' })
    }
  } catch (err) {
    findings.push(finding(SEVERITY.WARN, 'interaction-form-failed',
      `Form interaction failed: ${err.message}`))
  } finally {
    await page.unroute('**/*').catch(() => {})
  }

  // --- 3. Mobile nav toggle (only matters on narrow viewports) ---
  try {
    const vw = page.viewportSize()?.width ?? 0
    if (vw > 0 && vw < 900) {
      const togglers = [
        'button[aria-label*="menu" i]',
        'button[aria-controls*="nav" i]',
        'button[aria-expanded="false"]',
        'button.hamburger',
        'button.menu-toggle',
        '[data-toggle="menu"]',
      ]
      for (const sel of togglers) {
        const loc = page.locator(sel).first()
        if (await loc.isVisible({ timeout: 200 }).catch(() => false)) {
          const errorsBefore = preErrors.length
          await loc.click({ timeout: 1000, force: true }).catch(() => {})
          await page.waitForTimeout(300)
          const newErrors = preErrors.slice(errorsBefore)
          if (newErrors.length) {
            findings.push(finding(SEVERITY.WARN, 'interaction-menu-error',
              `Mobile menu toggle produced errors`, { selector: sel, errors: newErrors.slice(0, 3) }))
          } else {
            log.push({ step: 'mobile-menu-opened', selector: sel })
          }
          break
        }
      }
    }
  } catch {}

  page.off('pageerror', onError)
  page.off('console', onConsole)
  page.off('request', onRequest)

  return { findings, log }
}
